enum PropertyStatus { forRent, forSale, forLease }

enum ListingPackage { basic, premium, featured }

class Property {
  final String id;
  final String title;
  final String type;
  final PropertyStatus status;
  final double price;
  final String district;
  final String area;
  final String shortDescription;
  final String? exactLocation;
  final String? ownerPhone;
  final String? ownerWhatsApp;
  final List<String> photos;
  final int? bedrooms;
  final int? bathrooms;
  final int? parkingSpaces;
  final double? plotSize;
  final double? floorSize;
  final bool isVerified;
  final bool isUnlocked;
  final ListingPackage listingPackage;
  final DateTime createdAt;
  final bool hasSecurity;
  final bool hasFurnishing;
  final bool hasInternet;
  final bool hasSwimmingPool;
  final double? latitude;
  final double? longitude;
  // Short-stay (Airbnb / Holiday) fields
  final bool isShortStay;
  final double? pricePerNight;
  final int? maxGuests;
  final int? minNights;
  final double? cleaningFee;
  final double? rating;
  final int? reviewCount;

  factory Property.fromJson(Map<String, dynamic> j) {
    const statusMap = {
      'for_rent': PropertyStatus.forRent,
      'for_sale': PropertyStatus.forSale,
      'for_lease': PropertyStatus.forLease,
    };
    const pkgMap = {
      'basic': ListingPackage.basic,
      'premium': ListingPackage.premium,
      'featured': ListingPackage.featured,
    };
    const typeMap = {
      'house': 'House',
      'apartment': 'Apartment',
      'office': 'Office',
      'land': 'Land',
      'warehouse': 'Warehouse',
      'commercial': 'Commercial',
      'short_stay': 'Airbnb',
      'holiday_apt': 'Holiday Apt',
    };
    final photos = <String>[];
    if (j['cover_photo'] != null) photos.add(j['cover_photo'] as String);
    if (j['photos'] is List) {
      for (final p in j['photos'] as List) {
        final url = p is Map ? p['url'] : p;
        if (url != null && !photos.contains(url)) photos.add(url.toString());
      }
    }
    return Property(
      id: j['id'].toString(),
      title: j['title'] as String,
      type: typeMap[j['type']] ?? (j['type'] as String),
      status: statusMap[j['status']] ?? PropertyStatus.forRent,
      price: (j['price'] as num).toDouble(),
      district: j['district'] as String,
      area: j['area'] as String,
      shortDescription: (j['description'] as String?) ?? '',
      exactLocation: j['exact_location'] as String?,
      ownerPhone: j['owner_phone'] as String?,
      ownerWhatsApp: j['owner_whatsapp'] as String?,
      photos: photos,
      bedrooms: j['bedrooms'] as int?,
      bathrooms: j['bathrooms'] as int?,
      parkingSpaces: j['parking_spaces'] as int?,
      plotSize: (j['plot_size'] as num?)?.toDouble(),
      floorSize: (j['floor_size'] as num?)?.toDouble(),
      isVerified: j['is_verified'] as bool? ?? false,
      isUnlocked: j['is_unlocked'] as bool? ?? false,
      listingPackage: pkgMap[j['listing_package']] ?? ListingPackage.basic,
      createdAt: DateTime.parse(j['created_at'] as String),
      hasSecurity: j['has_security'] as bool? ?? false,
      hasFurnishing: j['has_furnishing'] as bool? ?? false,
      hasInternet: j['has_internet'] as bool? ?? false,
      hasSwimmingPool: j['has_swimming_pool'] as bool? ?? false,
      latitude: (j['latitude'] as num?)?.toDouble(),
      longitude: (j['longitude'] as num?)?.toDouble(),
      isShortStay: j['is_short_stay'] as bool? ?? false,
      pricePerNight: (j['price_per_night'] as num?)?.toDouble(),
      maxGuests: j['max_guests'] as int?,
      minNights: j['min_nights'] as int?,
      cleaningFee: (j['cleaning_fee'] as num?)?.toDouble(),
      rating: (j['rating'] as num?)?.toDouble(),
      reviewCount: j['review_count'] as int?,
    );
  }

  const Property({
    required this.id,
    required this.title,
    required this.type,
    required this.status,
    required this.price,
    required this.district,
    required this.area,
    required this.shortDescription,
    this.exactLocation,
    this.ownerPhone,
    this.ownerWhatsApp,
    required this.photos,
    this.bedrooms,
    this.bathrooms,
    this.parkingSpaces,
    this.plotSize,
    this.floorSize,
    this.isVerified = false,
    this.isUnlocked = false,
    this.listingPackage = ListingPackage.basic,
    required this.createdAt,
    this.hasSecurity = false,
    this.hasFurnishing = false,
    this.hasInternet = false,
    this.hasSwimmingPool = false,
    this.latitude,
    this.longitude,
    this.isShortStay = false,
    this.pricePerNight,
    this.maxGuests,
    this.minNights,
    this.cleaningFee,
    this.rating,
    this.reviewCount,
  });

  String get statusLabel {
    switch (status) {
      case PropertyStatus.forRent:
        return 'For Rent';
      case PropertyStatus.forSale:
        return 'For Sale';
      case PropertyStatus.forLease:
        return 'For Lease';
    }
  }

  String get priceLabel {
    if (isShortStay && pricePerNight != null) {
      final n = pricePerNight!;
      final f = n >= 1000000
          ? '${(n / 1000000).toStringAsFixed(1)}M'
          : n >= 1000
              ? '${(n / 1000).toStringAsFixed(0)}K'
              : n.toStringAsFixed(0);
      return 'UGX $f/night';
    }
    final formatted = price >= 1000000
        ? '${(price / 1000000).toStringAsFixed(1)}M'
        : price >= 1000
            ? '${(price / 1000).toStringAsFixed(0)}K'
            : price.toStringAsFixed(0);
    return status == PropertyStatus.forRent
        ? 'UGX $formatted/mo'
        : 'UGX $formatted';
  }

  String get shortStayBadge =>
      type == 'Holiday Apt' ? 'Holiday' : 'Airbnb';
}

// Sample data — photos use bundled asset paths
final List<Property> sampleProperties = [
  Property(
    id: '1',
    title: 'Modern 3BR House in Kololo',
    type: 'House',
    status: PropertyStatus.forRent,
    price: 2500000,
    district: 'Kampala',
    area: 'Kololo',
    shortDescription:
        'Spacious 3-bedroom house in a serene neighborhood with garden and parking.',
    exactLocation: 'Plot 14, Acacia Avenue, Kololo, Kampala',
    ownerPhone: '+256 701 234 567',
    ownerWhatsApp: '+256 701 234 567',
    photos: [
      'assets/images/prop1.jpg',
      'assets/images/prop3.jpg',
    ],
    bedrooms: 3,
    bathrooms: 2,
    parkingSpaces: 2,
    floorSize: 180,
    isVerified: true,
    listingPackage: ListingPackage.featured,
    createdAt: DateTime(2025, 6, 1),
    hasSecurity: true,
    hasFurnishing: false,
    hasInternet: true,
    latitude: 0.3241,
    longitude: 32.5825,
  ),
  Property(
    id: '2',
    title: 'Executive Apartment – Ntinda',
    type: 'Apartment',
    status: PropertyStatus.forRent,
    price: 1200000,
    district: 'Kampala',
    area: 'Ntinda',
    shortDescription:
        '2-bedroom executive apartment on 4th floor with city views.',
    exactLocation: 'Ntinda Shopping Mall Road, Kampala',
    ownerPhone: '+256 772 345 678',
    ownerWhatsApp: '+256 772 345 678',
    photos: [
      'assets/images/prop2.jpg',
      'assets/images/prop7.jpg',
    ],
    bedrooms: 2,
    bathrooms: 2,
    isVerified: true,
    listingPackage: ListingPackage.premium,
    createdAt: DateTime(2025, 6, 3),
    hasInternet: true,
    hasSecurity: true,
    latitude: 0.3380,
    longitude: 32.6070,
  ),
  Property(
    id: '3',
    title: '50x100 Plot – Wakiso',
    type: 'Land',
    status: PropertyStatus.forSale,
    price: 85000000,
    district: 'Wakiso',
    area: 'Gayaza Road',
    shortDescription:
        'Prime mailo land 50×100 ft, ready title, near tarmac road.',
    exactLocation: 'Gayaza Road, Km 12, Wakiso',
    ownerPhone: '+256 752 456 789',
    ownerWhatsApp: '+256 752 456 789',
    photos: [
      'assets/images/prop5.jpg',
    ],
    plotSize: 50 * 100,
    isVerified: false,
    listingPackage: ListingPackage.basic,
    createdAt: DateTime(2025, 6, 5),
    latitude: 0.4100,
    longitude: 32.6200,
  ),
  Property(
    id: '4',
    title: '5BR Villa with Pool – Muyenga',
    type: 'House',
    status: PropertyStatus.forSale,
    price: 650000000,
    district: 'Kampala',
    area: 'Muyenga',
    shortDescription:
        'Luxury 5-bed villa with private pool, gym, and panoramic views of Lake Victoria.',
    exactLocation: 'Plot 8, Tank Hill Road, Muyenga, Kampala',
    ownerPhone: '+256 701 567 890',
    ownerWhatsApp: '+256 701 567 890',
    photos: [
      'assets/images/prop4.jpg',
      'assets/images/prop8.jpg',
      'assets/images/prop1.jpg',
    ],
    bedrooms: 5,
    bathrooms: 4,
    parkingSpaces: 4,
    floorSize: 450,
    isVerified: true,
    listingPackage: ListingPackage.featured,
    createdAt: DateTime(2025, 6, 2),
    hasSecurity: true,
    hasFurnishing: true,
    hasInternet: true,
    hasSwimmingPool: true,
    latitude: 0.2950,
    longitude: 32.6030,
  ),
  Property(
    id: '5',
    title: 'Office Space – Nakasero',
    type: 'Office',
    status: PropertyStatus.forLease,
    price: 3500000,
    district: 'Kampala',
    area: 'Nakasero',
    shortDescription:
        'Grade A office space, 200 sqm, fully fitted, prime business district.',
    exactLocation: 'Nakasero Road, Plot 3, Kampala',
    ownerPhone: '+256 700 678 901',
    ownerWhatsApp: '+256 700 678 901',
    photos: [
      'assets/images/prop6.jpg',
      'assets/images/prop3.jpg',
    ],
    floorSize: 200,
    isVerified: true,
    listingPackage: ListingPackage.premium,
    createdAt: DateTime(2025, 6, 4),
    hasInternet: true,
    hasSecurity: true,
    latitude: 0.3160,
    longitude: 32.5780,
  ),
  Property(
    id: '6',
    title: 'Studio Apartment – Bukoto',
    type: 'Apartment',
    status: PropertyStatus.forRent,
    price: 600000,
    district: 'Kampala',
    area: 'Bukoto',
    shortDescription:
        'Cozy furnished studio, great for young professionals, close to amenities.',
    exactLocation: 'Bukoto Street, Plot 22, Kampala',
    ownerPhone: '+256 789 789 012',
    ownerWhatsApp: '+256 789 789 012',
    photos: [
      'assets/images/prop7.jpg',
      'assets/images/prop2.jpg',
    ],
    bedrooms: 1,
    bathrooms: 1,
    isVerified: false,
    listingPackage: ListingPackage.basic,
    createdAt: DateTime(2025, 6, 5),
    hasFurnishing: true,
    latitude: 0.3370,
    longitude: 32.5950,
  ),
  Property(
    id: '7',
    title: '4BR Townhouse – Naguru',
    type: 'House',
    status: PropertyStatus.forRent,
    price: 3200000,
    district: 'Kampala',
    area: 'Naguru',
    shortDescription:
        'Newly built 4-bedroom townhouse in a gated community with garden.',
    exactLocation: 'Naguru Hill, Plot 5, Kampala',
    ownerPhone: '+256 712 890 123',
    ownerWhatsApp: '+256 712 890 123',
    photos: [
      'assets/images/prop8.jpg',
      'assets/images/prop4.jpg',
    ],
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    floorSize: 250,
    isVerified: true,
    listingPackage: ListingPackage.premium,
    createdAt: DateTime(2025, 6, 6),
    hasSecurity: true,
    hasInternet: true,
    latitude: 0.3300,
    longitude: 32.6050,
  ),
  // ── Extra properties for richer map ──────────────────────────────────────
  Property(
    id: '8',
    title: '3BR Apartment – Bugolobi',
    type: 'Apartment',
    status: PropertyStatus.forRent,
    price: 1800000,
    district: 'Kampala',
    area: 'Bugolobi',
    shortDescription: 'Modern apartment with balcony and lake views.',
    exactLocation: 'Bugolobi Flats, Block C, Kampala',
    ownerPhone: '+256 701 000 001',
    ownerWhatsApp: '+256 701 000 001',
    photos: ['assets/images/prop2.jpg', 'assets/images/prop3.jpg'],
    bedrooms: 3,
    bathrooms: 2,
    floorSize: 140,
    isVerified: true,
    listingPackage: ListingPackage.premium,
    createdAt: DateTime(2025, 6, 6),
    hasInternet: true,
    hasSecurity: true,
    latitude: 0.3050,
    longitude: 32.6120,
  ),
  Property(
    id: '9',
    title: 'Commercial Warehouse – Nalukolongo',
    type: 'Warehouse',
    status: PropertyStatus.forLease,
    price: 8000000,
    district: 'Kampala',
    area: 'Nalukolongo',
    shortDescription: 'Large industrial warehouse, 1,000 sqm, near industrial area.',
    exactLocation: 'Nalukolongo Industrial Area, Kampala',
    ownerPhone: '+256 702 000 002',
    ownerWhatsApp: '+256 702 000 002',
    photos: ['assets/images/prop6.jpg'],
    floorSize: 1000,
    isVerified: true,
    listingPackage: ListingPackage.basic,
    createdAt: DateTime(2025, 6, 4),
    hasSecurity: true,
    latitude: 0.2980,
    longitude: 32.5500,
  ),
  Property(
    id: '10',
    title: '2BR House – Kira Town',
    type: 'House',
    status: PropertyStatus.forRent,
    price: 900000,
    district: 'Wakiso',
    area: 'Kira',
    shortDescription: 'Affordable 2-bedroom house in quiet Kira estate.',
    exactLocation: 'Kira Town Council, Wakiso',
    ownerPhone: '+256 703 000 003',
    ownerWhatsApp: '+256 703 000 003',
    photos: ['assets/images/prop1.jpg', 'assets/images/prop8.jpg'],
    bedrooms: 2,
    bathrooms: 1,
    parkingSpaces: 1,
    floorSize: 90,
    isVerified: false,
    listingPackage: ListingPackage.basic,
    createdAt: DateTime(2025, 6, 5),
    latitude: 0.3630,
    longitude: 32.6390,
  ),
  Property(
    id: '11',
    title: 'Luxury Penthouse – Skyz Hotel Area',
    type: 'Apartment',
    status: PropertyStatus.forRent,
    price: 6500000,
    district: 'Kampala',
    area: 'Naguru',
    shortDescription: 'Top-floor penthouse with 360° city views, fully serviced.',
    exactLocation: 'Skyz Hotel Road, Naguru, Kampala',
    ownerPhone: '+256 704 000 004',
    ownerWhatsApp: '+256 704 000 004',
    photos: ['assets/images/prop4.jpg', 'assets/images/prop7.jpg'],
    bedrooms: 4,
    bathrooms: 3,
    parkingSpaces: 2,
    floorSize: 320,
    isVerified: true,
    listingPackage: ListingPackage.featured,
    createdAt: DateTime(2025, 6, 3),
    hasSecurity: true,
    hasFurnishing: true,
    hasInternet: true,
    hasSwimmingPool: true,
    latitude: 0.3268,
    longitude: 32.6015,
  ),
  Property(
    id: '12',
    title: '100x100 Mailo Land – Entebbe Rd',
    type: 'Land',
    status: PropertyStatus.forSale,
    price: 220000000,
    district: 'Wakiso',
    area: 'Entebbe Road',
    shortDescription: 'Large corner plot on Entebbe Road with ready title.',
    exactLocation: 'Km 8, Entebbe Road, Wakiso',
    ownerPhone: '+256 705 000 005',
    ownerWhatsApp: '+256 705 000 005',
    photos: ['assets/images/prop5.jpg'],
    plotSize: 100 * 100,
    isVerified: true,
    listingPackage: ListingPackage.premium,
    createdAt: DateTime(2025, 6, 2),
    latitude: 0.2620,
    longitude: 32.5390,
  ),
  Property(
    id: '13',
    title: 'Shop Space – Kikuubo',
    type: 'Commercial',
    status: PropertyStatus.forRent,
    price: 2200000,
    district: 'Kampala',
    area: 'Kikuubo',
    shortDescription: 'Ground-floor shop in Kampala\'s busiest trading hub.',
    exactLocation: 'Kikuubo Lane, Kampala CBD',
    ownerPhone: '+256 706 000 006',
    ownerWhatsApp: '+256 706 000 006',
    photos: ['assets/images/prop6.jpg', 'assets/images/prop3.jpg'],
    floorSize: 45,
    isVerified: true,
    listingPackage: ListingPackage.basic,
    createdAt: DateTime(2025, 6, 6),
    hasSecurity: true,
    latitude: 0.3136,
    longitude: 32.5814,
  ),
  Property(
    id: '14',
    title: '5BR Mansion – Lubowa',
    type: 'House',
    status: PropertyStatus.forSale,
    price: 1200000000,
    district: 'Wakiso',
    area: 'Lubowa',
    shortDescription: 'Grand 5-bedroom mansion in Lubowa Estate with landscaped gardens.',
    exactLocation: 'Lubowa Estate, Entebbe Road, Wakiso',
    ownerPhone: '+256 707 000 007',
    ownerWhatsApp: '+256 707 000 007',
    photos: ['assets/images/prop8.jpg', 'assets/images/prop4.jpg', 'assets/images/prop1.jpg'],
    bedrooms: 5,
    bathrooms: 5,
    parkingSpaces: 6,
    floorSize: 600,
    plotSize: 50 * 100,
    isVerified: true,
    listingPackage: ListingPackage.featured,
    createdAt: DateTime(2025, 6, 1),
    hasSecurity: true,
    hasFurnishing: true,
    hasInternet: true,
    hasSwimmingPool: true,
    latitude: 0.2490,
    longitude: 32.5660,
  ),
  Property(
    id: '15',
    title: 'Studio – Makerere Hill',
    type: 'Apartment',
    status: PropertyStatus.forRent,
    price: 450000,
    district: 'Kampala',
    area: 'Makerere',
    shortDescription: 'Affordable studio near Makerere University, ideal for students.',
    exactLocation: 'Makerere Hill Road, Kampala',
    ownerPhone: '+256 708 000 008',
    ownerWhatsApp: '+256 708 000 008',
    photos: ['assets/images/prop2.jpg'],
    bedrooms: 1,
    bathrooms: 1,
    isVerified: false,
    listingPackage: ListingPackage.basic,
    createdAt: DateTime(2025, 6, 6),
    hasFurnishing: true,
    latitude: 0.3354,
    longitude: 32.5685,
  ),

  // ── Airbnb & Holiday Apartments ──────────────────────────────────────────
  Property(
    id: '16',
    title: 'Luxury Airbnb – Kololo Hill',
    type: 'Airbnb',
    status: PropertyStatus.forRent,
    price: 120000,
    district: 'Kampala',
    area: 'Kololo',
    shortDescription:
        'Stunning 2-bedroom Airbnb in the heart of Kololo. Fully furnished with rooftop terrace, fast Wi-Fi and city views. Perfect for business or leisure stays.',
    exactLocation: 'Kololo Hill Drive, Kampala',
    ownerPhone: '+256 701 100 001',
    ownerWhatsApp: '+256 701 100 001',
    photos: ['assets/images/prop1.jpg', 'assets/images/prop3.jpg'],
    bedrooms: 2,
    bathrooms: 2,
    floorSize: 110,
    isVerified: true,
    listingPackage: ListingPackage.featured,
    createdAt: DateTime(2025, 6, 7),
    hasFurnishing: true,
    hasInternet: true,
    hasSecurity: true,
    latitude: 0.3250,
    longitude: 32.5830,
    isShortStay: true,
    pricePerNight: 120000,
    maxGuests: 4,
    minNights: 1,
    cleaningFee: 30000,
    rating: 4.9,
    reviewCount: 87,
  ),
  Property(
    id: '17',
    title: 'Modern Airbnb Studio – Ntinda',
    type: 'Airbnb',
    status: PropertyStatus.forRent,
    price: 75000,
    district: 'Kampala',
    area: 'Ntinda',
    shortDescription:
        'Cozy self-contained studio for solo travellers or couples. Has a kitchenette, smart TV and secure parking.',
    exactLocation: 'Ntinda Road, Kampala',
    ownerPhone: '+256 702 100 002',
    ownerWhatsApp: '+256 702 100 002',
    photos: ['assets/images/prop2.jpg', 'assets/images/prop7.jpg'],
    bedrooms: 1,
    bathrooms: 1,
    floorSize: 45,
    isVerified: true,
    listingPackage: ListingPackage.premium,
    createdAt: DateTime(2025, 6, 6),
    hasFurnishing: true,
    hasInternet: true,
    latitude: 0.3390,
    longitude: 32.6080,
    isShortStay: true,
    pricePerNight: 75000,
    maxGuests: 2,
    minNights: 1,
    cleaningFee: 20000,
    rating: 4.7,
    reviewCount: 53,
  ),
  Property(
    id: '18',
    title: 'Airbnb Villa with Pool – Muyenga',
    type: 'Airbnb',
    status: PropertyStatus.forRent,
    price: 280000,
    district: 'Kampala',
    area: 'Muyenga',
    shortDescription:
        '4-bedroom villa with private pool and lake views. Ideal for groups, family reunions or corporate retreats.',
    exactLocation: 'Tank Hill Road, Muyenga, Kampala',
    ownerPhone: '+256 703 100 003',
    ownerWhatsApp: '+256 703 100 003',
    photos: ['assets/images/prop4.jpg', 'assets/images/prop8.jpg'],
    bedrooms: 4,
    bathrooms: 3,
    floorSize: 300,
    isVerified: true,
    listingPackage: ListingPackage.featured,
    createdAt: DateTime(2025, 6, 5),
    hasFurnishing: true,
    hasInternet: true,
    hasSecurity: true,
    hasSwimmingPool: true,
    latitude: 0.2960,
    longitude: 32.6010,
    isShortStay: true,
    pricePerNight: 280000,
    maxGuests: 8,
    minNights: 2,
    cleaningFee: 60000,
    rating: 4.8,
    reviewCount: 42,
  ),
  Property(
    id: '19',
    title: 'Holiday Apartment – Munyonyo',
    type: 'Holiday Apt',
    status: PropertyStatus.forRent,
    price: 180000,
    district: 'Kampala',
    area: 'Munyonyo',
    shortDescription:
        'Serene 3-bed holiday apartment steps from Lake Victoria. Wake up to lake breeze, enjoy sunset from your balcony.',
    exactLocation: 'Munyonyo Commonwealth Resort Road, Kampala',
    ownerPhone: '+256 704 100 004',
    ownerWhatsApp: '+256 704 100 004',
    photos: ['assets/images/prop6.jpg', 'assets/images/prop2.jpg'],
    bedrooms: 3,
    bathrooms: 2,
    floorSize: 160,
    isVerified: true,
    listingPackage: ListingPackage.featured,
    createdAt: DateTime(2025, 6, 4),
    hasFurnishing: true,
    hasInternet: true,
    hasSecurity: true,
    latitude: 0.2710,
    longitude: 32.5960,
    isShortStay: true,
    pricePerNight: 180000,
    maxGuests: 6,
    minNights: 2,
    cleaningFee: 40000,
    rating: 4.9,
    reviewCount: 61,
  ),
  Property(
    id: '20',
    title: 'Holiday Cottage – Entebbe',
    type: 'Holiday Apt',
    status: PropertyStatus.forRent,
    price: 350000,
    district: 'Wakiso',
    area: 'Entebbe',
    shortDescription:
        'Charming lakeshore cottage near Entebbe International Airport and botanical gardens. Perfect weekend getaway.',
    exactLocation: 'Lakeshore Drive, Entebbe',
    ownerPhone: '+256 705 100 005',
    ownerWhatsApp: '+256 705 100 005',
    photos: ['assets/images/prop5.jpg', 'assets/images/prop1.jpg'],
    bedrooms: 3,
    bathrooms: 2,
    floorSize: 140,
    isVerified: true,
    listingPackage: ListingPackage.featured,
    createdAt: DateTime(2025, 6, 3),
    hasFurnishing: true,
    hasInternet: true,
    hasSwimmingPool: true,
    latitude: 0.0539,
    longitude: 32.4635,
    isShortStay: true,
    pricePerNight: 350000,
    maxGuests: 6,
    minNights: 2,
    cleaningFee: 70000,
    rating: 5.0,
    reviewCount: 29,
  ),
  Property(
    id: '21',
    title: 'Holiday Suite – Naguru',
    type: 'Holiday Apt',
    status: PropertyStatus.forRent,
    price: 150000,
    district: 'Kampala',
    area: 'Naguru',
    shortDescription:
        'Stylish 2-bedroom holiday suite in quiet Naguru, close to restaurants and Skyz Hotel.',
    exactLocation: 'Naguru Hill, Kampala',
    ownerPhone: '+256 706 100 006',
    ownerWhatsApp: '+256 706 100 006',
    photos: ['assets/images/prop3.jpg', 'assets/images/prop6.jpg'],
    bedrooms: 2,
    bathrooms: 1,
    floorSize: 95,
    isVerified: false,
    listingPackage: ListingPackage.premium,
    createdAt: DateTime(2025, 6, 7),
    hasFurnishing: true,
    hasInternet: true,
    latitude: 0.3280,
    longitude: 32.6020,
    isShortStay: true,
    pricePerNight: 150000,
    maxGuests: 4,
    minNights: 1,
    cleaningFee: 25000,
    rating: 4.6,
    reviewCount: 18,
  ),
];
